---@class PackageVersionConfig
---@field color? ColorConfig
---@field spinner? SpinnerConfig
---@field docker? DockerConfig
---@field timeout? number
---
---@class ColorConfig
---@field wanted? string
---@field latest? string
---@field current? string
---@field abandoned? string
---
---@class SpinnerConfig
---@field type? "pacman" | "ball" | "space" | "minimal" | "dino"
---
---@class DockerConfig
---@field composer_container_name? string
---@field npm_container_name? string
---@field yarn_container_name? string
---@field pnpm_container_name? string

---@class TimeoutTimer
---@field stop fun()
---@field close fun()
