---@class PackageVersionConfig
---@field color? ColorConfig
---@field spinner? SpinnerConfig
---@field docker? DockerConfig
---
---@class ColorConfig
---@field wanted? string
---@field latest? string
---@field current? string
---@field abandoned? string
---
---@class SpinnerConfig
---@field relative? string
---@field type? "pacman" | "ball" | "space" | "minimal" | "dino"
---@field style? string
---@field width? integer
---@field height? integer
---@field column? integer
---@field row? integer
---
---@class DockerConfig
---@field composer_container_name? string
---@field npm_container_name? string
---@field yarn_container_name? string
---@field pnpm_container_name? string
